
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - "27037:6379"

  catalog:
    build:
      context: .
      dockerfile: src/Services/CatalogService/Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - "80"

  ocelotgw:
    build:
      context: .
      dockerfile: src/Gateways/OcelotApiGw/Dockerfile
    depends_on:
      - mongo
      - catalog
      - redis
    ports:
      - 27057:80

  monitoring:
    build:
      context: .
      dockerfile: src/Services/MonitoringService/Dockerfile
    depends_on:
      - catalog
    ports:
      - 27077:80